### ISSUE TITLE
How to get wavefront obj from an photo?

### ISSUE THREAD

**Issue by blx0102** [mikecokina/puppet-warp#2]
Hi bro, I'm trying to use your lib to change pose of photo like in photoshop. But how can I get the obj file from my photo? I can get the mask of the person by some background remove tools.

**Comment by mikecokina** [comment]
Hi, I used Blender for such purpose. But you will have to do  create mesh manually. It is quite annoying, but I do not know any generic or simplest tool for it.

**Comment by blx0102** [comment]
@mikecokina ok, thanks anyway!
