### ISSUE TITLE
Triangle version does not exist

### ISSUE THREAD

**Issue by arambianton** [mikecokina/puppet-warp#4]
You have a new version of Triangle in the requirements. However, on the main site it is not there and when you try to pip install puppet-warp, it gives me the error that there is no such version

**Comment by mikecokina** [comment]
@arambianton Tested for all python versions listed in README.md (3.7|3.8|3.9) with pip v20.0.2 and I found no issue. What python version and package manager do yo have?

**Comment by arambianton** [comment]
I had a newer pip version. However, I installed v20.0.2 and I get this error:
`ERROR: Could not find a version that satisfies the requirement triangle==20220202 (from puppet-warp) (from versions: 2013.01.06.linux-x86_64, 0.1, 0.2, 0.3, 2012.7.4, 2013.1.6a0, 2013.1.6, 2013.1.7, 2013.4.5, 2015.3.28, 2015.12.13, 2015.12.14, 20160202, 20160203, 20170106, 20170429, 20190115, 20190115.1, 20190115.2, 20190115.3, 20200325, 20200404, 20200424)
ERROR: No matching distribution found for triangle==20220202`. 

I have Python v3.9.6

**Comment by mikecokina** [comment]
@arambianton My python version is 3.9.16, however, I decreased requirements for triangle version to 20200424. I am running Ubuntu 20.04, and version 20200424 required built at least on my system, so package python3.9-dev was required. 
I released new version so please run `pip3 install puppet-warp==0.2` Hopefully it helps.

**Comment by arambianton** [comment]
Thanks, it works properly now and I could download your package!
