### ISSUE TITLE
problems installing the project

### ISSUE THREAD

**Issue by arambianton** [mikecokina/puppet-warp#5]
I have recently changed the macOS and Python versions as the versions of other libraries failed on the previous versions. When I try to install the library, I get this issue in opencv-contrib-python==4.5.4.60: ERROR: No matching distribution found for numpy==1.21.2. 
I have tried to install all the requirements manually and then install the puppet-warp library without including the dependencies. However, I am getting a few issues:
1) When I try to install triangle==20200424, I get ERROR: Failed building wheel for triangle. I have tried to install "Wheel" and have tried many ways to solve this problem, but nothing helps
2) When installing opencv-contrib-python==4.5.4.60, I get ERROR: No matching distribution found for numpy==1.21.2
I understand that the second problem isn't probably in your hands, but I would appreciate a help in this issue. Thanks and have a great day!

**Comment by mikecokina** [comment]
I updated requirements not to be so restrictive to versions. I tested it just very very briefly. You can install latest version from git with command `pip3 install git+https://github.com/mikecokina/puppet-warp.git`. However, I am not able to help with triangle. Most likely missing dependencies for package (compiler, linker, any library). It is related to triangle itself, not to this package.

**Comment by mikecokina** [comment]
@arambianton `triangle` is not mandatory anymore. I re-implemented triangular mesh via `scipy.spatial.Delaunay`. There is also extended README, take a look.
