### ISSUE TITLE
opencv version

### ISSUE THREAD

**Issue by wyardley** [mikecokina/puppet-warp#9]
I can see 4240ed25a89c901bb5b498536fecb46169889c5c, however, with `puppet-warp` v0.2, which seems to be the latest, I get this error:
```
ERROR: Cannot install opencv-python==4.7.0.72 and puppet-warp==0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested opencv-python==4.7.0.72
    puppet-warp 0.2 depends on opencv-python==4.5.4.60
```

Also, I'll note that there's a newer version of opencv as well (4.9.0.80 is current), though not sure if it's been tested:
https://pypi.org/project/opencv-python/

**Comment by mikecokina** [comment]
Could you please provide more information about the Python version and operating system you are using?

**Comment by wyardley** [comment]
I can, but don't think it's relevant here? I think the issue is just that a release was never cut post 0.2, so the changes from 4240ed25a89c901bb5b498536fecb46169889c5c and 8d459c341ed58b295262dabea20fcf3bba447fef are not included in any available versioned release?

If it helps, Python 3.10 or 3.11 on OS X or Ubuntu Linux.

Would it be possible to cut a 0.3 off current trunk branch?

**Comment by mikecokina** [comment]
Oh man, you're right. Thank you. I'll do a quick release to avoid issues for anyone in the future. I'm not planning to test the latest version of OpenCV right now, maybe in the future.

**Comment by wyardley** [comment]
Awesome. Thanks so much!

**Comment by mikecokina** [comment]
Okay, it's done. Hopefully, there won't be any more dependency issues for some time.
